Bookstore/Components/CartSummaryViewComponent.cs
using System;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bookstore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket basket;

        public CartSummaryViewComponent(Basket basketService)
        {
            basket = basketService;
        }

        public IViewComponentResult Invoke()
        {
            return View(basket);
        }
    }
}

Bookstore/Components/CategoriesViewComponent.cs
using System;
using System.Linq;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bookstore.Components
{
    public class CategoriesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public CategoriesViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            var categories = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(categories);
        }
    }
}

Bookstore/Views/Shared/ProjectSummary.cshtml
@{
}

@model Books


<div class="card m-auto" style="width: 18rem;">
    <div class="text-center">
        <h4 class="card-header">@Model.Title</h4>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Author: @Model.Author</li>
        <li class="list-group-item">Publisher: @Model.Publisher</li>
        <li class="list-group-item">ISBN: @Model.Isbn</li>
        <li class="list-group-item">Classification: @Model.Classification</li>
        <li class="list-group-item">Category: @Model.Category</li>
        <li class="list-group-item">Page Count: @Model.PageCount</li>
        <li class="list-group-item">Price: @Model.Price</li>
    </ul>
    <form method="post" asp-page="/Cart">

        <input type="hidden" asp-for="@Model.BookId" />
        @*<input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />*@

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-right">Add to Cart</button>
        </span>

    </form>
</div>
<br />
<br />

Bookstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookstore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookstore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <vc:cart-summary />
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:categories></vc:categories>
        </div>

        <div class="col-6">
            <div>
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2022 - Bookstore - John Critchlow Productions
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>